// Sistema de permisos RBAC
export const PERMISSIONS = {
  ITEM_LIST: 'ITEM_LIST',
  ITEM_DETAIL: 'ITEM_DETAIL',
  ITEM_CREATE: 'ITEM_CREATE',
  ITEM_EDIT: 'ITEM_EDIT',
  ITEM_DEACTIVATE: 'ITEM_DEACTIVATE',
  FAVORITES_USE: 'FAVORITES_USE',
  PROFILE_VIEW: 'PROFILE_VIEW',
  PROFILE_EDIT: 'PROFILE_EDIT',
  ADMIN_PANEL_VIEW: 'ADMIN_PANEL_VIEW',
};

// Definición de roles y sus permisos
export const ROLE_PERMISSIONS = {
  USER: [
    PERMISSIONS.ITEM_LIST,
    PERMISSIONS.ITEM_DETAIL,
    PERMISSIONS.FAVORITES_USE,
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.PROFILE_EDIT,
  ],
  ADMIN: [
    PERMISSIONS.ITEM_LIST,
    PERMISSIONS.ITEM_DETAIL,
    PERMISSIONS.ITEM_CREATE,
    PERMISSIONS.ITEM_EDIT,
    PERMISSIONS.ITEM_DEACTIVATE,
    PERMISSIONS.FAVORITES_USE,
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.PROFILE_EDIT,
    PERMISSIONS.ADMIN_PANEL_VIEW,
  ],
  PROFESOR: [
    PERMISSIONS.ITEM_LIST,
    PERMISSIONS.ITEM_DETAIL,
    PERMISSIONS.ITEM_EDIT,
    PERMISSIONS.FAVORITES_USE,
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.PROFILE_EDIT,
  ],
};
